pip3 install --no-dependencies /tmp/packages/rpds_py-0.20.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
pip3 install --no-dependencies /tmp/packages/attrs-24.2.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/referencing-0.35.1-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/traitlets-5.14.3-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/platformdirs-4.3.6-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/pkgutil_resolve_name-1.3.10-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jsonschema_specifications-2023.12.1-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyter_core-5.7.2-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jsonschema-4.23.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/fastjsonschema-2.20.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/tornado-6.4.1-cp38-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl
pip3 install --no-dependencies /tmp/packages/pyzmq-26.2.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
pip3 install --no-dependencies /tmp/packages/pycparser-2.22-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/webencodings-0.5.1-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/nbformat-5.10.4-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyter_client-8.6.3-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/MarkupSafe-2.1.5-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
pip3 install --no-dependencies /tmp/packages/soupsieve-2.6-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/ptyprocess-0.7.0-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/cffi-1.17.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
pip3 install --no-dependencies /tmp/packages/tinycss2-1.4.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/pygments-2.18.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/pandocfilters-1.5.1-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/nbclient-0.10.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/mistune-3.0.2-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyterlab_pygments-0.3.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jinja2-3.1.4-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/defusedxml-0.7.1-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/bleach-6.1.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/beautifulsoup4-4.12.3-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/terminado-0.18.1-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/rfc3986_validator-0.1.1-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/rfc3339_validator-0.1.4-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/PyYAML-6.0.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
pip3 install --no-dependencies /tmp/packages/python_json_logger-2.0.7-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/argon2_cffi_bindings-21.2.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
pip3 install --no-dependencies /tmp/packages/typing_extensions-4.12.2-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/sniffio-1.3.1-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/idna-3.10-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/exceptiongroup-1.2.2-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/pure_eval-0.2.3-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/executing-2.1.0-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/asttokens-2.4.1-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/wcwidth-0.2.13-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/parso-0.8.4-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/websocket_client-1.8.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/Send2Trash-1.8.3-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/prometheus_client-0.21.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/overrides-7.7.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/nbconvert-7.16.4-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyter_server_terminals-0.5.3-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyter_events-0.10.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/argon2_cffi-23.1.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/anyio-4.5.2-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/urllib3-2.2.3-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/charset_normalizer-3.4.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
pip3 install --no-dependencies /tmp/packages/certifi-2024.8.30-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/stack_data-0.6.3-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/prompt_toolkit-3.0.48-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/pickleshare-0.7.5-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/pexpect-4.9.0-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/matplotlib_inline-0.1.7-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jedi-0.19.1-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/decorator-5.1.1-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/backcall-0.2.0-py2.py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/h11-0.14.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyter_server-2.14.2-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/requests-2.32.3-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/json5-0.9.25-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/babel-2.16.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/psutil-6.1.0-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl
pip3 install --no-dependencies /tmp/packages/nest_asyncio-1.6.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/ipython-8.12.3-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/debugpy-1.8.7-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl
pip3 install --no-dependencies /tmp/packages/comm-0.2.2-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/httpcore-1.0.6-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/tomli-2.0.2-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/notebook_shim-0.2.4-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyterlab_server-2.27.3-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyter_lsp-2.2.5-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/ipykernel-6.29.5-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/httpx-0.27.2-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/async_lru-2.0.4-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyterlab-4.3.0-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/widgetsnbextension-4.0.13-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyterlab_widgets-3.0.13-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/notebook-7.2.2-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyter_console-6.6.3-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/ipywidgets-8.1.5-py3-none-any.whl
pip3 install --no-dependencies /tmp/packages/jupyter-1.1.1-py2.py3-none-any.whl
